dist: trusty
language: python
python:
  - "3.7"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"
  - tox
after_success:
  - pip install codecov
  - codecov
cache: pip
notifications:
  email: true

deploy:
  provider: pypi
  user: hellysmile
  password:
    secure: "nDk2zl6oboaVJXakDDiChTXlLneM+Neqcqz+/t9eT+vU4c7N7Bhv3ONlm+W2PFsqLfLA4yTLweO7TG9+9nh7sKyneJkNUw4Srald7AFoBwhy/LERHw2FJUC1FbteWv+GiHPoz3lYAZKROG3rK/6nBeyivdDIteZf+W3YKo1wk3c="
  distributions: "sdist upload"
  on:
    tags: true
    all_branches: true
    python: 3.7
